step1_data-preprocessing:
  data_dir: /home/anglil/data/dqa/shining3
  target_dir: data/s3
  glove_path: /home/anglil/models/glove/glove.6B.300d.txt
  min_count: 5
  vgg_model_path: ~/models/vgg/vgg-19.caffemodel
  vgg_proto_path: ~/models/vgg/vgg-19.prototxt
  debug: 'False'
  qa2hypo: 'True'
  qa2hypo_path: ../dqa/qa2hypo
  prepro_images: 'True'
step2_trainning:
  model_name: m05
  data_dir: data/s3
  fold_path: data/s3/folds/fold23.json
  batch_size: 100
  init_mean: 0
  init_std: 0.1
  init_lr: 0.1
  anneal_period: 20
  anneal_ratio: 0.5
  num_epochs: 200
  opt: basic
  val_num_batches: -1
  train_num_batches: -1
  test_num_batches: -1
  device_type: cpu
  num_devices: 1
  val_period: 5
  save_period: 10
  config: None
  config_ext: .json
  hidden_size: 50
  image_size: 4096
  rnn_num_layers: 1
  emb_num_layers: 0
  keep_prob: 1.0
  sim_func: dot
  lstm: basic
  forget_bias: 2.5
  cell_clip: 40
  rand_y: 1.0
  mode: dqanet
  encoder: lstm
step3_testing:
  model_name: m05
  data_dir: data/s3
  fold_path: data/s3/folds/fold23.json
  batch_size: 100
  init_mean: 0
  init_std: 0.1
  init_lr: 0.1
  anneal_period: 20
  anneal_ratio: 0.5
  num_epochs: 200
  opt: basic
  val_num_batches: -1
  train_num_batches: -1
  test_num_batches: -1
  device_type: cpu
  num_devices: 1
  val_period: 5
  save_period: 10
  config: None
  config_ext: .json
  hidden_size: 50
  image_size: 4096
  rnn_num_layers: 1
  emb_num_layers: 0
  keep_prob: 1.0
  sim_func: dot
  lstm: basic
  forget_bias: 2.5
  cell_clip: 40
  rand_y: 1.0
  mode: dqanet
  encoder: lstm
